name: LMEye
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.01.10=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1t=h7f8727e_0
  - pip=23.0.1=py38h06a4308_0
  - python=3.8.10=h12debd9_8
  - readline=8.2=h5eee18b_0
  - setuptools=66.0.0=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - certifi==2023.5.7
    - charset-normalizer==3.1.0
    - clip==1.0
    - filelock==3.12.0
    - fsspec==2023.5.0
    - ftfy==6.1.1
    - huggingface-hub==0.14.1
    - idna==3.4
    - numpy==1.24.3
    - opencv-python==4.7.0.72
    - packaging==23.1
    - pillow==9.5.0
    - pyyaml==6.0
    - regex==2023.5.5
    - requests==2.30.0
    - sentencepiece==0.1.99
    - tokenizers==0.13.3
    - torch==1.13.1+cu116
    - torchaudio==0.13.1+cu116
    - torchvision==0.14.1+cu116
    - tqdm==4.65.0
    - transformers==4.29.0
    - typing-extensions==4.5.0
    - urllib3==2.0.2
    - wcwidth==0.2.6
